Repository proxystore/proxystore, pull requests merged in 2023-06, with the labels that each got.

#321 Adding lock to register store factory
  proxystore/store/base.py
Labels: bug

#322 Bump to ProxyStore v0.5.1
  pyproject.toml
Labels: ignore-for-release, package

#323 Bump to v0.5.2dev1
  .github/pull_request_template.md
  pyproject.toml
Labels: internal, development, ignore-for-release

#326 Add zenodo badge
  README.md
Labels: documentation
