Repository proxystore/proxystore, pull requests merged in 2023-09, with the labels that each got.

#356 Fix flakey relay client tests
  tests/p2p/relay_client_test.py
  tests/p2p/relay_test.py
Labels: internal, ignore-for-release

#358 Correct unit conversion from ns
  proxystore/timer.py
Labels: bug

#363 Enable dependency injection model for relay client with `PeerManager` and `PeerConnection`
  docs/api/cli.md
  proxystore/endpoint/endpoint.py
  proxystore/p2p/__init__.py
  proxystore/p2p/connection.py
  proxystore/p2p/manager.py
  proxystore/p2p/relay/__init__.py
  proxystore/p2p/relay/basic/__init__.py
  proxystore/p2p/relay/basic/client.py
  proxystore/p2p/relay/basic/server.py
  proxystore/p2p/relay/protocols.py
  pyproject.toml
  testing/relay_server.py
  testing/scripts/peer_connection_bandwidth.py
  testing/scripts/peer_manager_bandwidth.py
  tests/integration/endpoints_test.py
  tests/p2p/connection_test.py
  tests/p2p/manager_test.py
  tests/p2p/relay/__init__.py
  tests/p2p/relay/basic/__init__.py
  tests/p2p/relay/basic/client_test.py
  tests/p2p/relay/basic/server_cli_test.py
  tests/p2p/relay/basic/server_test.py
Labels: enhancement, breaking

#365 Enable dependency injection model for `PeerManager` and `Endpoint`
  docs/guides/endpoints-debugging.md
  proxystore/endpoint/endpoint.py
  proxystore/endpoint/serve.py
  proxystore/p2p/relay/basic/client.py
  testing/endpoint.py
  testing/scripts/peer_endpoint_bandwidth.py
  tests/endpoint/endpoint_peering_test.py
  tests/endpoint/endpoint_solo_test.py
  tests/endpoint/serve_test.py
  tests/integration/endpoints_test.py
  tests/p2p/relay/basic/server_cli_test.py
Labels: enhancement, breaking

#367 Refactor Globus authentication tools
  docs/api/cli.md
  proxystore/connectors/globus.py
  proxystore/globus.py
  proxystore/globus/__init__.py
  proxystore/globus/cli.py
  proxystore/globus/client.py
  proxystore/globus/manager.py
  proxystore/globus/scopes.py
  proxystore/globus/storage.py
  proxystore/globus/transfer.py
  pyproject.toml
  testing/connectors.py
  tests/connectors/globus_test.py
  tests/globus/__init__.py
  tests/globus/cli_test.py
  tests/globus/client_test.py
  tests/globus/conftest.py
  tests/globus/manager_test.py
  tests/globus/scopes_test.py
  tests/globus/storage_test.py
  tests/globus/transfer_test.py
  tests/globus_test.py
Labels: enhancement, internal, breaking

#368 Fix typo in method name of `GlobusAuthManager`
  proxystore/globus/manager.py
Labels: bug, ignore-for-release

#369 Refactor `proxystore.p2p` and `proxystore.utils`
  docs/guides/endpoints-debugging.md
  docs/guides/endpoints.md
  proxystore/connectors/endpoint.py
  proxystore/connectors/globus.py
  proxystore/connectors/multi.py
  proxystore/endpoint/cli.py
  proxystore/endpoint/client.py
  proxystore/endpoint/commands.py
  proxystore/endpoint/endpoint.py
  proxystore/endpoint/serve.py
  proxystore/globus/storage.py
  proxystore/p2p/connection.py
  proxystore/p2p/exceptions.py
  proxystore/p2p/manager.py
  proxystore/p2p/relay/basic/client.py
  proxystore/p2p/relay/basic/server.py
  proxystore/p2p/relay/exceptions.py
  proxystore/p2p/relay/messages.py
  proxystore/p2p/relay/protocols.py
  proxystore/store/base.py
  proxystore/utils/__init__.py
  proxystore/utils/counter.py
  proxystore/utils/data.py
  proxystore/utils/environment.py
  proxystore/utils/imports.py
  proxystore/utils/tasks.py
  proxystore/utils/timer.py
  testing/connectors.py
  testing/scripts/peer_connection_bandwidth.py
  tests/endpoint/cli_test.py
  tests/endpoint/serve_test.py
  tests/p2p/connection_test.py
  tests/p2p/manager_test.py
  tests/p2p/relay/basic/client_test.py
  tests/p2p/relay/basic/server_test.py
  tests/p2p/relay/messages_test.py
  tests/utils/__init__.py
  tests/utils/counter_test.py
  tests/utils/data_test.py
  tests/utils/environment_test.py
  tests/utils/imports_test.py
  tests/utils/tasks_test.py
  tests/utils/timer_test.py
Labels: internal, breaking

#373 Make endpoints support Globus Auth relays (#62)
  proxystore/endpoint/cli.py
  proxystore/endpoint/commands.py
  proxystore/endpoint/config.py
  proxystore/endpoint/serve.py
  tests/endpoint/serve_test.py
Labels: enhancement

#374 Use TOML for endpoint and relay configuration files
  docs/guides/endpoints-debugging.md
  docs/guides/relay-serving.md
  proxystore/connectors/endpoint.py
  proxystore/endpoint/cli.py
  proxystore/endpoint/commands.py
  proxystore/endpoint/config.py
  proxystore/endpoint/serve.py
  proxystore/p2p/relay/config.py
  proxystore/p2p/relay/run.py
  pyproject.toml
  testing/endpoint.py
  tests/endpoint/cli_test.py
  tests/endpoint/commands_test.py
  tests/endpoint/config_test.py
  tests/endpoint/serve_test.py
  tests/integration/endpoints_test.py
  tests/p2p/relay/config_test.py
Labels: breaking, package

#375 Migrate DIM connectors to extensions package
  .github/workflows/integration.yml
  README.md
  docs/contributing/index.md
  docs/installation.md
  docs/known-issues.md
  mkdocs.yml
  proxystore/connectors/dim.py
  proxystore/connectors/dim/__init__.py
  proxystore/connectors/dim/exceptions.py
  proxystore/connectors/dim/margo.py
  proxystore/connectors/dim/models.py
  proxystore/connectors/dim/ucx.py
  proxystore/connectors/dim/utils.py
  proxystore/connectors/dim/zmq.py
  pyproject.toml
  testing/connectors.py
  testing/mocked/pymargo.py
  testing/mocked/ucx.py
  testing/mocking.py
  tests/conftest.py
  tests/connectors/dim/__init__.py
  tests/connectors/dim/margo_test.py
  tests/connectors/dim/ucx_test.py
  tests/connectors/dim/zmq_test.py
  tests/connectors/dim_test.py
  tox.ini
Labels: breaking

#378 Fix flakey unit tests
  tests/conftest.py
  tests/endpoint/commands_test.py
  tests/p2p/relay/run_test.py
Labels: internal

#379 Set default relay address and update endpoints guide
  docs/guides/endpoints.md
  proxystore/endpoint/cli.py
  proxystore/endpoint/commands.py
  tests/endpoint/cli_test.py
Labels: documentation, enhancement

#380 Improve logging when tokens are missing on endpoint start
  docs/guides/endpoints.md
  proxystore/endpoint/serve.py
  tests/endpoint/serve_test.py
Labels: enhancement

#381 Bump to ProxyStore v0.6.0
  pyproject.toml
Labels: ignore-for-release, package

#382 Bump to ProxyStore v0.6.1dev1
  pyproject.toml
Labels: ignore-for-release, package
