Repository proxystore/proxystore, pull requests merged in 2023-05, with the labels that each got.

#288 Add a Globus Compute guide
  docs/concepts/connector.md
  docs/concepts/proxy.md
  docs/concepts/store.md
  docs/css/extra.css
  docs/get-started.md
  docs/guides/endpoints-debugging.md
  docs/guides/endpoints.md
  docs/guides/globus-compute.md
  docs/guides/index.md
  docs/guides/performance.md
  mkdocs.yml
Labels: documentation

#291 Adjust PR tags and release template
  .github/dependabot.yml
  .github/pull_request_template.md
  .github/release.yml
  .pre-commit-config.yaml
Labels: development

#293 Refactor distributed in-memory connectors
  proxystore/connectors/dim/__init__.py
  proxystore/connectors/dim/exceptions.py
  proxystore/connectors/dim/margo.py
  proxystore/connectors/dim/models.py
  proxystore/connectors/dim/ucx.py
  proxystore/connectors/dim/utils.py
  proxystore/connectors/dim/zmq.py
  proxystore/p2p/relay.py
  pyproject.toml
  testing/connectors.py
  testing/mocked/pymargo.py
  testing/mocked/ucx.py
  testing/mocking.py
  tests/conftest.py
  tests/connectors/dim/margo_test.py
  tests/connectors/dim/ucx_test.py
  tests/connectors/dim/zmq_test.py
  tests/connectors/endpoint_test.py
  tests/connectors/globus_test.py
  tox.ini
Labels: internal, development, breaking

#297 Revert MacOS multiprocessing to default
  tests/conftest.py
Labels: development, ignore-for-release

#299 Limit mkdocstrings-python version to <1.0
  pyproject.toml
Labels: documentation, ignore-for-release

#298 Made interface optional for DIMs and added `addr` arg for IP
  proxystore/connectors/dim/margo.py
  proxystore/connectors/dim/ucx.py
  proxystore/connectors/dim/utils.py
  proxystore/connectors/dim/zmq.py
  testing/connectors.py
  testing/mocked/pymargo.py
  testing/mocked/ucx.py
  tests/connectors/dim/margo_test.py
  tests/connectors/dim/ucx_test.py
  tests/connectors/dim/zmq_test.py
Labels: enhancement

#300 Bump to ProxyStore v0.5.0
  pyproject.toml
Labels: ignore-for-release, package

#301 Bump to ProxyStore v0.5.1dev1
  pyproject.toml
Labels: ignore-for-release, package

#302 Add a spawn Margo server shortcut
  proxystore/connectors/dim/margo.py
  testing/connectors.py
  tests/connectors/dim/margo_test.py
Labels: bug, ignore-for-release

#305 Revert #299 by fixing mkdocstrings-python change
  docs/_templates/python/material/function.html
  pyproject.toml
Labels: documentation, ignore-for-release

#307 Add missing citation
  docs/publications/index.md
Labels: documentation, ignore-for-release

#308 Update known issues page
  docs/known-issues.md
Labels: documentation, ignore-for-release

#309 Fix example syntax error and add mypy notes
  docs/get-started.md
  docs/known-issues.md
Labels: documentation

#314 Fix docstrings rendering as raw HTML
  docs/_templates/python/material/function.html
Labels: documentation

#315 Avoid proxying singleton types (`True`, `False`, `None`)
  proxystore/proxy.py
  proxystore/store/base.py
  proxystore/store/exceptions.py
  tests/store/store_proxy_test.py
Labels: bug, breaking

#317 Add `store_registration()` context manager
  proxystore/store/__init__.py
  tests/store/init_test.py
Labels: enhancement

#318 Refactor and simplify `Store` unit tests
  testing/stores.py
  tests/conftest.py
  tests/store/init_test.py
  tests/store/shims_test.py
  tests/store/store_basics_test.py
  tests/store/store_metrics_test.py
  tests/store/store_proxy_test.py
Labels: internal

#320 Add `clear` flag to `Connector` implementations that support it
  proxystore/connectors/file.py
  proxystore/connectors/globus.py
  proxystore/connectors/redis.py
  proxystore/store/base.py
  testing/mocked/redis.py
  tests/connectors/file_test.py
  tests/connectors/globus_test.py
  tests/connectors/redis_test.py
Labels: enhancement
