Repository proxystore/proxystore, pull requests merged in 2024-07, with the labels that each got.

#592 Add Proxy Patterns preprint to publications
  README.md
  docs/publications/index.md
Labels: documentation

#594 Refactor serialization logic
  proxystore/serialize.py
  tests/serialize_test.py
Labels: internal

#595 Improve serialization performance with buffers and custom type support
  proxystore/serialize.py
  pyproject.toml
  tests/serialize_test.py
Labels: enhancement

#597 Bump to ProxyStore v0.7.0
  pyproject.toml
Labels: package

#598 Bump to ProxyStore v0.7.1dev1
  pyproject.toml
Labels: package

#602 Exclude state by default in `LocalConnector` config
  proxystore/connectors/local.py
  tests/connectors/multi_test.py
  tests/store/store_proxy_test.py
Labels: bug
